### ISSUE TITLE
markdown not converted to text 

### ISSUE THREAD

**Issue by rubytastic** [schneems/maildown#10]
With mail_view this markdown:

```
## You're almost there <%= @resource.username.capitalize %>!
```
renders correctly in html but in text just shows as is 

```
## You're almost there <%= @resource.username.capitalize %>!
```

What do I do wrong? Using rails 4

**Comment by jgrau** [comment]
Let's keep those issue counts down - I say close this issue. It's old. It's stale. The reproduction/example files are no longer available. Having zero issues would be nice. :)

**Comment by schneems** [comment]
Seems fine. If you have an app that reproduces the problem send it this way and we can re-open. Thanks for the bump!
