### ISSUE TITLE
Markdown not Markdowned by Kramdown

### ISSUE THREAD

**Issue by sfcgeorge** [schneems/maildown#26]
The Markdown views are run through Kramdown (et al) for rendering to HTML format, but for Text format the original Markdown is returned unprocessed. 

This makes sense insofar as Markdown is already nicely readable text, but Kramdown provides some desirable options to transform Markdown. Specifically, I put `<style>` tags in my view / template then use [Roadie](https://github.com/Mange/roadie-rails) to correctly inline that in the HTML, but I want to strip the style tags from the Markdown. 

Like all good Rubyists, I monkeypatched it in `config/initializers/maildown.rb`

```ruby
require "maildown"

module Maildown
  class Md
    def to_text
      Kramdown::Document.new(string).tap(&:to_remove_html_tags).to_kramdown
    end
  end
end
```

To ship this officially in the gem the API for supplying an custom Markdown renderer would need to change slightly. There would also have to be a way to specify which options you actually want to use. 

Perhaps that's more complexity than it's worth. Perhaps just making this a "well documented monkeypatch" would suffice, an orangutangpatch if you will. Plus some care not to change the `to_text` api. 

You may not consider this a bug so feel free to close and anyone searching will find _the snippet_.

**Comment by schneems** [comment]
Would probably expose a method that gets called that the user can over-write


```
def to_text
  document = Kramdown::Document.new(string)
  Maildown.user_format(document)
end
```

Or something, where someone could take the incoming document and do whatever they want to it.


```
# config/initializers/maildown.rb
Maildown.user_format = -> (document) {
  document.tap(&:to_remove_html_tags).to_kramdown
}
```

If you want to give me a patch, i'm fine supporting it.

**Comment by sfcgeorge** [comment]
Hiya,

Okay! I like the `user_format` idea, that's nice. The slight catch is in customising the Markdown processor as currently `.to_html` is called in the block so we couldn't use the custom renderer in the `to_text` or `user_format`. This is the current snippet from readme for setting custom render engine:

```ruby
Maildown::MarkdownEngine.set do |text|
  carpet = Redcarpet::Markdown.new(Redcarpet::Render::HTML, {})
  carpet.render(text).html_safe
end
```

### Options I can think of

Simply add a new renderer block config that corresponds to the `to_text` option: 

```ruby
# default:
Maildown::MarkdownEngine.set_text do |text|
  text
end

# custom config:
Maildown::MarkdownEngine.set_text do |text|
  Kramdown::Document.new(text).tap(&:to_remove_html_tags).to_kramdown
end
```

and maybe alias `set` to `set_html` for symmetry, perhaps with a deprecation.

Or the engine setter could be changed to not call `to_html` immediately and we do that internally and then the `user_format` can be added etc. I actually think the above might be easiest and most flexible though, without needing to deprecate or break anything. Thoughts?
