### ISSUE TITLE
Breaks local email delivery

### ISSUE THREAD

**Issue by sfcgeorge** [schneems/maildown#28]
This is a weird one (sorry). Adding the Maildown gem breaks local email delivery into `tmp/mails`. Removing the gem and they start saving again. It doesn't cause any issues in production, and the dev `/rails/mailers` preview works fine. So real email sending and rendering is fine, but local delivery breaks.

The only monkeypatch Maildown does to Rails is in [lib/maildown/ext/action_mailer.rb](https://github.com/schneems/maildown/blob/master/lib/maildown/ext/action_mailer.rb) and that's only 17 LOC. So I went through commenting and uncommenting bits of that file until I found the culprit is [line 3](https://github.com/schneems/maildown/blob/master/lib/maildown/ext/action_mailer.rb#L3)

```ruby
mail_view_klass = ActionMailer::Base.view_context_class
```

Which is weird as that barely does anything. The method `view_context_class` is included from several files deep with Rails and has some funky stuff in it like an anonymous class. But maybe the issue is nothing to do with that method; could it be a load order / autoloading thing? 

I'm at a bit of a loss, any thoughts?

**Comment by schneems** [comment]
No clue. How are you doing local mail delivery? I use `mail_view` to preview emails.

**Comment by sfcgeorge** [comment]
Just `config.action_mailer.delivery_method = :file` I think.

**Comment by sfcgeorge** [comment]
I found a way to make it work. Simply add config for `file_settings`. I don't know why it isn't needed without Maildown, then adding Maildown breaks file delivery until that config is added. I don't see any Maildown code that should interfere so it seems it might be a bug in Rails, easy to work around anyway so closing issue.

**config/environments/development.rb**
```ruby
config.action_mailer.delivery_method = :file
# config.action_mailer.perform_deliveries = true # not needed it seems
config.action_mailer.file_settings = {
  location: Rails.root.join("tmp/mails")
}
```
