### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by cgat** [schneems/maildown#36]
The `gemspec` seems to indicate that actionmailer greater than 4.0.0 is supported, while the readme says that support is for Rails 5.0 +.  Looking through some of the issues it seems at least some people use (or used) this with Rails 4+. Would love some clarification as this.

**Comment by schneems** [comment]
If you check the blame you'll see that was added in https://github.com/schneems/maildown/pull/30. which links to #29. So it should still work with 4.0. I only use it on a 5.0+ project. When 5.2 is released 4.2 is entirely unmaintained and subject to security vulnerabilities. 4.0 is already unmaintained for quite some time. You need to upgrade to 5.0 soon.

**Comment by cgat** [comment]
Right, thanks for the suggestion on how I could have figured this out myself (blame).

For what it's worth, on 4.2.9 (which I'm using), when I set `Maildown.enable_layouts = true` in an initializer and run my action mailer I'm seeing an exception:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
from /Users/cgat/.rvm/gems/ruby-2.4.1/gems/actionview-4.2.9/lib/action_view/layouts.rb:319:in `_layout'
```
The mailer works when `enable_layouts` is not set.

**Comment by schneems** [comment]
Ahh, I’ve only tested that feature with 5.0 it’s pretty hacky as implemented.
