### ISSUE TITLE
Possible race condition in the Maildown::MarkdownEngine.default_html_block method

### ISSUE THREAD

**Issue by yuki24** [schneems/maildown#40]
I was wondering how https://github.com/yuki24/did_you_mean/issues/102 could occur. One thing I noticed is that in the maildown gem, the `kramdown` gem is lazily loaded on the fly, which adds a handful of constants dynamically. In an extreme condition, this may cause a race condition. Consider the following scenario where a Sidekiq instance runs two threads (workders) that attempt to run an email delivery job:

Thread 1 | Thread 2
---------|---------
| calls `MarkdownEngine.default_html_block` | - |
| - | calls `MarkdownEngine.default_html_block` |
| [attempts to `require 'kramdown'`](https://github.com/schneems/maildown/blob/2ea4c8e7a1b3bcf7b84d3f43405ed0ae5e4c5be5/lib/maildown/markdown_engine.rb#L52) for the first time | - |
| evaluates [the line that adds a `Kramdown` constant](https://github.com/gettalong/kramdown/blob/84102c8b654a54eb8307fe7703b1414b537eb016/lib/kramdown/document.rb#L46) but [doesn't reach the line 74 that adds `Kramdown::Document`](https://github.com/gettalong/kramdown/blob/REL_1_16_2/lib/kramdown/document.rb#L74) | - |
| - | [evaluates `unless defined? Kramdown`](https://github.com/schneems/maildown/blob/2ea4c8e7a1b3bcf7b84d3f43405ed0ae5e4c5be5/lib/maildown/markdown_engine.rb#L52) (now evaluates to `unless true`) |
| - | attempts to call [`html_block.call` on the proc that has a reference to the `Kramdown::Document`](https://github.com/schneems/maildown/blob/2ea4c8e7a1b3bcf7b84d3f43405ed0ae5e4c5be5/lib/maildown/markdown_engine.rb#L24) that does not exist yet |

In this scenario, the thread 2 would raise a `NameError` because the `Kramdown` constant is loaded but the `Kramdown::Document` is not. Also, it would only occur once after a cold reboot since the constant would be available once it's loaded by the thread 1.

I wasn't sure what fixes you'd prefer, so just wanted to bring this up. Thanks!

**Comment by schneems** [comment]
Thanks for the note. The reason that it's a lazy load is that people can install their own markdown rendering engines if they want (though honestly I have no proof that anyone is doing that.

I think the fix would be requiring the gem at boot time, but rescuing in-case it does not exist. The only other thing I could think of is to use a mutex to block multiple clients from trying to require at the same time, but that increases a tiny bit of runtime overhead that I don't think is needed.

**Comment by schneems** [comment]
Do you know if Autoload fixes this issue, or if I need to mutex it?

**Comment by yuki24** [comment]
I was late by a hair, but you may have to mutex it. There is a thread-safety issue in `Autoload` https://bugs.ruby-lang.org/issues/12688 and the example in the issue happens to reproduce the exact same issue you saw a few days ago. Not sure that was fixed.

cc @ko1

**Comment by schneems** [comment]
Looks like it is threadsafe https://twitter.com/schneems/status/978705647301746688

**Comment by bf4** [comment]
It's supposed to have been thread safe since 2.0 https://github.com/headius/thread_safe/issues/15#issuecomment-28936120
