### ISSUE TITLE
Mailer Class Works, Custom Mailer class does not unfortunately

### ISSUE THREAD

**Issue by justindunn** [schneems/maildown#44]
I'm working on an application that has a regular mailer.rb file in the app/mailers directory, and also has a second mailer called notification_mailer.rb, which inherits from mailer class 
```class NotificationMailer < Mailer```
When emails are sent through the normal mailer, the css is rendered inline into the layout like it should and the html rules are applied correctly. When emails are sent through the custom notification_mailer.rb, the css does not render inline to the html and no html is rendered, and the stylesheet tag is still in the header in the source on those emails, on the ones that rendered inline they did not.

**Comment by schneems** [comment]
Please provide an example app that demonstrates the issue.

![cfda1413-74eb-49cd-8743-8bed83bbf413](https://user-images.githubusercontent.com/59744/42642367-55b77754-85bc-11e8-9f4e-6642fdd732f5.gif)

**Comment by justindunn** [comment]
I can't send the app i'm working on because of legal reasons, I can create a sample app if needed still, but I think I've traced my problem maybe to premailer, since its the css that is not working correctly

**Comment by schneems** [comment]
I don’t want your app. I want the smallest possible thing that shows the
problem.

**Comment by justindunn** [comment]
Ok I've got 2 mailer classes:
```class Mailer < Company::Mailer```
```class NotificationMailer < Mailer```
and then application_mailer.rb
```# frozen_string_literal: true

# Top-level mailer class.
class ApplicationMailer < ActionMailer::Base
  layout 'mailer'
end```
I also have a custom mailer in lib lib/company/mailer.rb

```class WeCounsel::Mailer < ApplicationMailer```

my layout is in app/views/layouts/mailer.md.erb and app/views/layouts/mailer.text.erb

**Comment by schneems** [comment]
I appreciate the issue, and I know i'm asking you to go to the extra mile, but I also own 52 published gems and it takes a LOT of time and effort every time I need to debug an issue. The one thing that helps speed up getting it fixed (if possible) is an app that works out of the box that shows the issue at hand. 

I need an example app, please. An app that is an example of what is going wrong with directions on how to run it.

**Comment by schneems** [comment]
Closing for now if you have an example app let me know and we can come back to it https://www.codetriage.com/example_app
